# Generated by Django 2.2.5 on 2019-10-09 23:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('ingredients', models.CharField(max_length=100)),
                ('flour', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=2)),
                ('eggs', models.DecimalField(decimal_places=1, max_digits=2)),
                ('butter', models.DecimalField(decimal_places=1, max_digits=2)),
                ('oil', models.DecimalField(decimal_places=1, max_digits=2)),
                ('margarine', models.DecimalField(decimal_places=1, max_digits=2)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('baker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakers.Baker')),
            ],
        ),
    ]
