# Generated by Django 2.2.5 on 2019-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Ingredients',
            field=models.TextField(blank=True),
        ),
    ]
